fix(BUILD-1287): repository ownership
SonarSource/sonarcloud_example_cpp-cmake-macos-otherci pull request #1
Opened 2022-02-02 17:54 UTC by julien-carsique-sonarsource

Set the team @SonarSource/sonarcloud as code owner in `.github/CODEOWNERS` file.

This is required by [BUILD-1271](https://jira.sonarsource.com/browse/BUILD-1271).
Contact @SonarSource/re-team for more information.

2022-02-07 09:55 UTC, claire-villard-sonarsource commented
@SonarSource/cfamily Aren't you owners of this repository, instead of the SC team? 
There are several similar PRs on other repositories, like [here](https://github.com/SonarSource/sonarcloud_example_cpp-cmake-windows-otherci) or [here](https://github.com/SonarSource/sonarcloud_example_cpp-cmake-windows-travis/pull/3), to do not create too much noise I'll use your answer on this PR to assign the appropriate reviewers on the other ones, if it makes sense for you.

2022-02-07 10:13 UTC, arseniy-sonar commented
Hi @claire-villard-sonarsource, [sonarcloud_example_cpp-*](https://github.com/SonarSource?q=sonarcloud_example_cpp&type=all&language=&sort=) repositories (including this one) are superseded by the repositories in https://github.com/sonarsource-cfamily-examples organization and should be achieved.
Is that correct, @geoffray-adde-sonarsource ?
EDIT:
Apparently some of the repositories are still referenced in SC, so should not be archived just yet. Sorry for the misinformation.

2022-02-07 17:25 UTC, claire-villard-sonarsource commented
> Apparently some of the repositories are still referenced in SC, so should not be archived just yet. Sorry for the misinformation.

Thanks for pointing it! I'll then review which repos are still used in SonarCloud, ask for archiving of those that are not used anymore and create SC tickets to migrate to the new repos for the others.

2022-02-07 17:39 UTC, gregaubert commented
@lucas-paulger-sonarsource Are those repos mentioned by @arseniy-sonar the once you are currently migrating as part of https://jira.sonarsource.com/browse/SC-4268 ?

2022-02-07 17:46 UTC, lucas-paulger-sonarsource commented
> @lucas-paulger-sonarsource Are those repos mentioned by @arseniy-sonar the once you are currently migrating as part of https://jira.sonarsource.com/browse/SC-4025 and https://jira.sonarsource.com/browse/SC-4268 ?

Yes this is exactly what I am working on updating now. I just merged in 
https://jira.sonarsource.com/browse/SC-4025  which should be the last live reference. and I'm working to get the new BitBucket and GitLab references in 
https://jira.sonarsource.com/browse/SC-4268

I'm reviewing any reference to `sonarcloud_example_cpp` and I'll make sure they aren't referenced anymore 👍🏻

2022-02-08 12:14 UTC, arseniy-sonar commented
And to answer your original question, @claire-villard-sonarsource. As we decided to keep these repositories until we migrate them to the new org, you can assign @SonarSource/cfamily as the owner of [sonarcloud_example_cpp-*](https://github.com/SonarSource?q=sonarcloud_example_cpp&type=all&language=&sort=) repositories.

2022-02-09 07:56 UTC, claire-villard-sonarsource commented
Thanks for your answers @arseniy-sonar ! I'll review all the PRs assigned to the SC team for those repos, and request changes accordingly.

2022-02-09 07:57 UTC, claire-villard-sonarsource requested changes

2022-02-09 07:57 UTC, claire-villard-sonarsource commented on .github/CODEOWNERS
> +* @sonarsource/sonarcloud
```suggestion
* @SonarSource/cfamily 
```

2022-03-10 11:28 UTC, julien-carsique-sonarsource commented on .github/CODEOWNERS
> +* @sonarsource/sonarcloud
```.github/CODEOWNERS @SonarSource/languages-team-cfamily```

2022-03-17 17:33 UTC, merged